### ISSUE TITLE
firefox rendering of menubar and featured articles/members

### ISSUE THREAD

**Issue by oktools** [rochacbruno-archive/Movuca#18]
this may not be a movuca-specific issue, but FIreFox fails to render certain components; the menubar falls back to a drop down list, which is workable; the featured items just do not show up

**Comment by rochacbruno** [comment]
are you using the default bootstrap layout? I will do some tests.

Thanks.

I am developing a brand new theme, more cleaner, (I hired up a designer to
do it for movu.ca, with dashboard and other tools)

On Tue, Jul 10, 2012 at 4:04 PM, oktools <
reply@reply.github.com

**Comment by oktools** [comment]
yes; the only thing I removed was the Cook Book menu item

this occurred on FF  3.6 on Windows 7 and whatever the current version
is on Ubuntu 12.4

On 7/10/12, Bruno Rocha
reply@reply.github.com
wrote:

**Comment by oktools** [comment]
OK, this isn't an issue; it's me not knowing how things work

I don't know why, yet, perhaps my FF browser windows were just smaller than the others; I hadn't realized that even Chrome will hide the aforementioned components if the window is too narrow
