### ISSUE TITLE
landing page after Register

### ISSUE THREAD

**Issue by ndegroot** [rochacbruno-archive/Movuca#2]
After filling in the registration-form as redirect to a non-existing adress occurs, namely http://movu.ca/demo/person/index  this should be http://movu.ca/demo/person/show Should be easy to fix, haven't looked at the code yet.
BTW this 'social CMS' looks great!

**Comment by rochacbruno** [comment]
Thank you for reporting, it is fixed!

self.settings.register_next = self.url('show') in modules/movuca.py Access class.
