### ISSUE TITLE
Error on saving profile info

### ISSUE THREAD

**Issue by fgmacedo** [rochacbruno-archive/Movuca#5]
After connecting with Google Account, I was asked to choose a user name. 
I wrote one login name then clicked on save button, the system crashed issuing a ticket: http://movu.ca/admin/default/ticket/demo/201.83.58.47.2012-02-07.16-29-13.bc4162c5-1588-4deb-98f9-cae92f174643

**Comment by fgmacedo** [comment]
Now when I try to get any page, the system crashes issuing a new ticket. 
For example:

http://movu.ca/demo/home/index
Ticket issued: demo/201.83.58.47.2012-02-07.16-35-08.e1ecd1ce-ded3-4ee0-9a4f-88de32719998

**Comment by rochacbruno** [comment]
FIXED!
