### ISSUE TITLE
Login with Facebook and Google always requesting permission

### ISSUE THREAD

**Issue by lucmult** [rochacbruno-archive/Movuca#8]
I'm using external login.

For both (Google and Facebook) when I click the "Connect!" buttons in the login box, they ask me again for permission.

It should ask permission just in the first time, after that use the gave permission straight away.

[],

Luciano Pacheco

**Comment by rochacbruno** [comment]
There is a flag in config.auth_options the default is "force" but it can be defined as "remember" and it will not ask for permissions again.
