### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by blye** [rochacbruno-archive/Movuca#9]
using web2py 1997 
i get the followingerror 
I have pulled the latest code, tried the zip, the same thing.

 File "G:/__WEB2PY 1993 B/web2py_win1997dev/web2py/applications/Movuca/models/4_extra.py", line 104
    SELECT(*[OPTION(option, _value=value) for value, option in [("article", T("Articles")), ("user", T("Users"))]], _name="kind", _id="kind"),_class="two columns alpha search-select"),
                                                                                                                        ^
SyntaxError: invalid syntax

the error appears to occur at the _name 
what am I doing wrong!

**Comment by rochacbruno** [comment]
Hi, what Python version are you using?

**Comment by blye** [comment]
thanks for your response. I had no time to test. It was a PATH issue.

**Comment by rochacbruno** [comment]
Can you say exactly what you did to solve this?
